# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:

  categories:
    - title: Exciting New Features 🎉
      labels:
        - feature

    - title: Bugs that shall be no more 🛠
      labels:
        - bug

    - title: Things that had to be done  ❤️‍🩹
      labels:
        - chore

    - title: Other Changes
      labels:
        - "*"
