# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - none
  categories:
    - title: Exciting New Features 🎉
      labels:
        - enhancement

    - title: Bugs that shall be no more 🛠
      labels:
        - bug

    - title: Things that had to be done  ❤️‍🩹
      labels:
        - chore

    - title: Other Changes
      labels:
        - "*"
  change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
  change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
  version-resolver:
    major:
      labels:
        

